FROM python:3.9
COPY /requirements.txt /
RUN apt update && apt install -y build-essential gcc clang clang-tools cmake python3-dev cppcheck valgrind afl \
     gcc-multilib libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender1 && \
     pip install --no-cache-dir -r /requirements.txt
COPY /app /
COPY /scripts/run_app.sh /
WORKDIR /app
ENTRYPOINT ["bash", "/run_app.sh"]